const actionTypes = Object.freeze({
    //app
    APP_START_UP_COMPLETE: 'APP_START_UP_COMPLETE',
    SET_CONTENT_OF_CONFIRM_MODAL: 'SET_CONTENT_OF_CONFIRM_MODAL',
    CHANGE_LANGUAGE: "CHANGE_LANGUAGE",
    //user
    ADD_USER_SUCCESS: 'ADD_USER_SUCCESS',
    USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
    USER_LOGIN_FAIL: 'USER_LOGIN_FAIL',
    PROCESS_LOGOUT: 'PROCESS_LOGOUT',

    //Book
    CREATE_BOOK_SUCCESS: 'CREATE_BOOK_SUCCESS',
    CREATE_BOOK_FAILED: 'CREATE_BOOK_FAILED',
    EDIT_BOOK_SUCCESS: 'EDIT_BOOK_SUCCESS',
    EDIT_BOOK_FAILED: 'EDIT_BOOK_FAILED',
    DELETE_BOOK_SUCCESS: 'DELETE_BOOK_SUCCESS',
    DELETE_BOOK_FAILED: 'DELETE_BOOK_FAILED',
    FETCH_ALL_BOOKS_SUCCESS: 'FETCH_ALL_BOOKS_SUCCESS',
    FETCH_ALL_BOOKS_FAILED: 'FETCH_ALL_BOOKS_FAILED',

    //Supplier
    CREATE_SUPPLIER_SUCCESS: 'CREATE_SUPPLIER_SUCCESS',
    CREATE_SUPPLIER_FAILED: 'CREATE_SUPPLIER_FAILED',
    EDIT_SUPPLIER_SUCCESS: 'EDIT_SUPPLIER_SUCCESS',
    EDIT_SUPPLIER_FAILED: 'EDIT_SUPPLIER_FAILED',
    DELETE_SUPPLIER_SUCCESS: 'DELETE_SUPPLIER_SUCCESS',
    DELETE_SUPPLIER_FAILED: 'DELETE_SUPPLIER_FAILED',
    FETCH_ALL_SUPPLIERS_SUCCESS: 'FETCH_ALL_SUPPLIERS_SUCCESS',
    FETCH_ALL_SUPPLIERS_FAILED: 'FETCH_ALL_SUPPLIERS_FAILED',

    //Customer
    CREATE_CUSTOMER_SUCCESS: 'CREATE_CUSTOMER_SUCCESS',
    CREATE_CUSTOMER_FAILED: 'CREATE_CUSTOMER_FAILED',
    EDIT_CUSTOMER_SUCCESS: 'EDIT_CUSTOMER_SUCCESS',
    EDIT_CUSTOMER_FAILED: 'EDIT_CUSTOMER_FAILED',
    DELETE_CUSTOMER_SUCCESS: 'DELETE_CUSTOMER_SUCCESS',
    DELETE_CUSTOMER_FAILED: 'DELETE_CUSTOMER_FAILED',
    FETCH_ALL_CUSTOMERS_SUCCESS: 'FETCH_ALL_CUSTOMERS_SUCCESS',
    FETCH_ALL_CUSTOMERS_FAILED: 'FETCH_ALL_CUSTOMERS_FAILED',

    //Employee
    CREATE_EMPLOYEE_SUCCESS: 'CREATE_EMPLOYEE_SUCCESS',
    CREATE_EMPLOYEE_FAILED: 'CREATE_EMPLOYEE_FAILED',
})

export default actionTypes;